name: Test Build Deploy
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  install-build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout of repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        # Tell pnpm to use cached downloads whenever possible instead of downloading from the server
        run: pnpm i --prefer-offline

      - name: Build
        run: pnpm build

  lint-test:
    name: Lint and Run unit tests
    runs-on: ubuntu-latest
    needs: install-build
    steps:
      - name: Checkout of repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        # Tell pnpm to use cached downloads whenever possible instead of downloading from the server
        run: pnpm i --prefer-offline

      - name: Lint package
        run: pnpm lint

      - name: Run tests
        run: pnpm test

  build-and-deploy-storybook:
    # permissions:
    #   pages: write
    #   id-token: write

    # environment:
    #   name: github-pages
    #   url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: install-build
    steps:
      - name: Checkout of repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm i --prefer-offline

      - name: Build Storybook
        run: pnpm build-storybook

      # - name: Deploy to GitHub Pages
      #   id: deployment
      #   uses: actions/deploy-pages@v4
