name: Test Build Deploy
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  install-build:
    name: Install dependencies and build app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout of repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        # Tell pnpm to use cached downloads whenever possible instead of downloading from the server
        run: pnpm i --prefer-offline

      - name: Build
        run: pnpm build

  lint-test:
    name: Lint and Run unit tests
    runs-on: ubuntu-latest
    needs: install-build
    steps:
      - name: Checkout of repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Lint package
        run: pnpm lint

      - name: Run tests
        run: pnpm test

  build-and-deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout of repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm install

      - name: Build Storybook
        run: pnpm build-storybook

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
